---
apiVersion: v1
kind: Service
metadata:
  name: emerald-citizen-postgres
  labels:
    app: emerald-citizen-postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: emerald-citizen-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emerald-citizen-postgres-deploy
spec:
  selector:
    matchLabels:
      app: emerald-citizen-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: emerald-citizen-postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: PGDATA
          value: /data
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: emerald-citizen-postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: emerald-citizen-postgres
              key: username
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pgdata
          mountPath: /datamount/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata
