apiVersion: v1
kind: Service
metadata:
  name: emerald-citizen-postgres
  namespace: stage-emerald-citizen
  labels:
    app: emerald-citizen-postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: emerald-citizen-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stage-emerald-citizen-postgres-deploy
  namespace: stage-emerald-citizen
spec:
  selector:
    matchLabels:
      app: emerald-citizen-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: emerald-citizen-postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        resources:
           limits:
              cpu: 0.25
              memory: 250Mi
           requests:
              cpu: 0.25
              memory: 250Mi
        env:
        - name: PGDATA
          value: /data
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: emerald-citizen-postgres
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: emerald-citizen-postgres
              key: username
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pgdata
          mountPath: /datamount/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
