---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emerald-citizen-deployment
  namespace: emerald-citizen
  labels:
    app: emerald-citizen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emerald-citizen
  template:
    metadata:
      labels:
        app: emerald-citizen
    spec:
      containers:
      - name: web-server
        image: mvpstudio/emerald-citizen:01cfcaa
        resources:
           limits:
              cpu: 0.25
              memory: 250Mi
           requests:
              cpu: 0.25
              memory: 250Mi
        ports:
        - containerPort: 8080
        env: 
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: emerald-citizen-postgres
              key: password
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: emerald-citizen-postgres
              key: username
        - name: DATABASE_HOST
          value: emerald-citizen-postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
