version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:9-alpine-ram
        environment:
          POSTGRES_USER: emcit
    steps:
      - checkout
      - run: yarn build
      - persist_to_workspace:
          root: ./
          # must include anything needed to build/tag/push docker image
          paths:
            - build
            - .mvpstudio
            - .git
            - kube

  publish:
    docker:
      - image: circleci/python:3
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          docker_layer_caching: true
      - run: curl https://raw.githubusercontent.com/MVPStudio/build_setup/scott/build_tag_push.sh | bash

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ./build-output
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ./gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}   
      - run:
          name: Deploy To Kubernetes
          command: |
            kubectl apply -f ./build-output/kube
            # TODO: it would be cool to parse all the yaml files, find all the deployments, and report rollout status
    
workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build
      - publish:
          context: dockerhub-publish
          requires:
            - build
      - deploy:
          context: k8-deploy
          requires:
            - publish
          filters:
            branches:
              only: master