---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: prod-emerald-citizen
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key
      containers:
        - name: web-server
          image: mvpstudio/emerald-citizen:f9b468f
          resources:
            limits:
              cpu: 0.25
              memory: 100Mi
            requests:
              cpu: 0.25
              memory: 100Mi
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: NODE_ENV
              value: production
            - name: HIDE_TEST_BANNER
              value: "true"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emerald-citizen-postgres
                  key: password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: emerald-citizen-postgres
                  key: username
            - name: DATABASE_HOST
              value: postgres
            - name: GOOGLE_MAPS_WEB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-maps-api-key
                  key: apikey
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: session-secret
                  key: secret
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: STORAGE_BUCKET
              value: prod-emerald-citizen
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: prod-emerald-citizen
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
